#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "In commit-msg"
npm run commitlint ${1}

# This does not seem to work
# Similar to this:
# npx --no -- commitlint --edit "$1"
# Test merge lint again
# Test simple message again